In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('other_data/Bank_Transaction_Fraud_Detection.csv')

In [3]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [4]:
df.shape

(200000, 24)

In [5]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Bank_Branch', 'Account_Type', 'Transaction_ID', 'Transaction_Date',
       'Transaction_Time', 'Transaction_Amount', 'Merchant_ID',
       'Transaction_Type', 'Merchant_Category', 'Account_Balance',
       'Transaction_Device', 'Transaction_Location', 'Device_Type', 'Is_Fraud',
       'Transaction_Currency', 'Customer_Contact', 'Transaction_Description',
       'Customer_Email'],
      dtype='object')

In [6]:
columns_to_drop = ["Customer_ID","Customer_Name", "Transaction_ID", "Merchant_ID","Customer_Contact","Transaction_Description", "Customer_Email", "Transaction_Currency"]
df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [7]:
df.head()

,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_Date,Transaction_Time,Transaction_Amount,Transaction_Type,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud
0,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,23-01-2025,16:04:07,32415.45,Transfer,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0
1,Female,51,Maharashtra,Nashik,Nashik Branch,Business,11-01-2025,17:14:53,43622.60,Bill Payment,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0
2,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,25-01-2025,03:09:52,63062.56,Bill Payment,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0
3,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,19-01-2025,12:27:02,14000.72,Debit,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0
4,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,30-01-2025,18:30:46,18335.16,Transfer,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  object
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  object
 3   City                  200000 non-null  object
 4   Bank_Branch           200000 non-null  object
 5   Account_Type          200000 non-null  object
 6   Transaction_Date      200000 non-null  object
 7   Transaction_Time      200000 non-null  object
 8   Transaction_Amount    200000 non-null  float64
 9   Transaction_Type      200000 non-null  object
 10  Merchant_Category     200000 non-null  object
 11  Account_Balance       200000 non-null  float64
 12  Transaction_Device    200000 non-null  object
 13  Transaction_Location  200000 non-null  object
 14  Device_Type           200000 non-null  object
 15  Is_Fraud              200000 non-null  int64
dtypes: float64(2), int64(2), object(12)
memory usage: 24.4+ MB

In [9]:
df["year"] = pd.to_datetime(df["Transaction_Date"]).dt.year
df["month"] = pd.to_datetime(df["Transaction_Date"]).dt.month
df["day"] = pd.to_datetime(df["Transaction_Date"]).dt.day

df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.hour
df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.minute
df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.second

df.drop(["Transaction_Time", "Transaction_Date"], axis=1, inplace=True)

/tmp/ipykernel_47451/1088819859.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["year"] = pd.to_datetime(df["Transaction_Date"]).dt.year
/tmp/ipykernel_47451/1088819859.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["month"] = pd.to_datetime(df["Transaction_Date"]).dt.month
/tmp/ipykernel_47451/1088819859.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["day"] = pd.to_datetime(df["Transaction_Date"]).dt.day

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  object
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  object
 3   City                  200000 non-null  object
 4   Bank_Branch           200000 non-null  object
 5   Account_Type          200000 non-null  object
 6   Transaction_Amount    200000 non-null  float64
 7   Transaction_Type      200000 non-null  object
 8   Merchant_Category     200000 non-null  object
 9   Account_Balance       200000 non-null  float64
 10  Transaction_Device    200000 non-null  object
 11  Transaction_Location  200000 non-null  object
 12  Device_Type           200000 non-null  object
 13  Is_Fraud              200000 non-null  int64
 14  year                  200000 non-null  int32
 15  month                 200000 non-null  int32
 16  day                   200000 non-null  int32
 17  hour                  200000 non-null  int32
dtypes: float64(2), int32(4), int64(2), object(10)
memory usage: 24.4+ MB

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

Gender                  0
Age                     0
State                   0
City                    0
Bank_Branch             0
Account_Type            0
Transaction_Amount      0
Transaction_Type        0
Merchant_Category       0
Account_Balance         0
Transaction_Device      0
Transaction_Location    0
Device_Type             0
Is_Fraud                0
year                    0
month                   0
day                     0
hour                    0
dtype: int64

In [13]:
Categorical = [i for i in df.columns if df[i].dtype == 'O']
Numerical = [i for i in df.columns if df[i].dtype != 'O']

In [14]:
print(f"Categorical: \n{Categorical}\n\nNumerical: \n{Numerical}")

Categorical:
['Gender', 'State', 'City', 'Bank_Branch', 'Account_Type', 'Transaction_Type', 'Merchant_Category', 'Transaction_Device', 'Transaction_Location', 'Device_Type']

Numerical:
['Age', 'Transaction_Amount', 'Account_Balance', 'Is_Fraud', 'year', 'month', 'day', 'hour']

In [24]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
label_encoder = LabelEncoder()
for i in Categorical:
    df[i] = label_encoder.fit_transform(df[i])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  int64
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  int64
 3   City                  200000 non-null  int64
 4   Bank_Branch           200000 non-null  int64
 5   Account_Type          200000 non-null  int64
 6   Transaction_Amount    200000 non-null  float64
 7   Transaction_Type      200000 non-null  int64
 8   Merchant_Category     200000 non-null  int64
 9   Account_Balance       200000 non-null  float64
 10  Transaction_Device    200000 non-null  int64
 11  Transaction_Location  200000 non-null  int64
 12  Device_Type           200000 non-null  int64
 13  Is_Fraud              200000 non-null  int64
 14  year                  200000 non-null  int32
 15  month                 200000 non-null  int32
 16  day                   200000 non-null  int32
 17  hour                  200000 non-null  int32
dtypes: float64(2), int32(4), int64(12)
memory usage: 24.4 MB

In [23]:
X = df.drop(columns=['Is_Fraud'])
Y = df["Is_Fraud"]

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.1)

In [25]:
scaler = StandardScaler()

scaled_data = scaler.fit_transform(x_train)
x_train_scaled = pd.DataFrame(scaled_data, columns=x_train.columns)

x_train_scaled

,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_Amount,Transaction_Type,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,year,month,day,hour
0,-1.004276,-1.635667,-0.564370,-1.568954,-1.568954,-1.225492,-0.638423,-0.704645,0.292787,-0.205523,-0.583413,-1.588245,1.340658,0.0,0.0,-0.174307,1.412215
1,-1.004276,-1.243419,1.169446,0.269140,0.269140,0.000116,-0.724040,0.002668,-1.462003,-1.652580,0.234699,0.271287,1.340658,0.0,0.0,-0.520381,-1.528599
2,-1.004276,-0.589673,1.067456,-0.256030,-0.256030,0.000116,-1.337867,0.002668,0.292787,1.144135,-0.419790,-0.246557,1.340658,0.0,0.0,-1.558604,0.028302
3,-1.004276,-0.785797,-1.074316,-1.282497,-1.282497,-1.225492,-1.133227,-1.411957,1.462646,0.874896,0.234699,-1.305784,0.446588,0.0,0.0,0.633200,0.201291
4,-1.004276,-0.589673,1.067456,0.674953,0.674953,0.000116,-1.220326,-1.411957,-0.877073,0.108704,-1.237902,0.671440,-0.447482,0.0,0.0,1.094633,0.547269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179995,0.995742,0.521696,0.149554,0.698824,0.698824,0.000116,-0.442717,0.709981,0.877716,-0.861717,0.561943,0.694978,0.446588,0.0,0.0,0.748558,0.143628
179996,0.995742,0.521696,1.577402,0.651081,0.651081,1.225724,1.210480,1.417294,0.292787,-1.518926,-1.401524,0.647901,-1.341552,0.0,0.0,0.171768,0.720258
179997,0.995742,-0.589673,-0.054424,-0.065059,-0.065059,-1.225492,1.680822,0.002668,-0.292143,-1.213239,1.707299,-0.058250,0.446588,0.0,0.0,1.209991,0.893247
179998,0.995742,0.783195,1.475413,0.436239,0.436239,-1.225492,-0.425208,1.417294,1.462646,-1.297645,-1.237902,0.436056,1.340658,0.0,0.0,0.863916,-0.721317
179999,0.995742,-0.262799,-1.278294,-1.377983,-1.377983,-1.225492,1.422682,-1.411957,0.292787,0.063815,-0.092546,-1.399937,0.446588,0.0,0.0,1.209991,-0.317676

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

In [28]:
log_model = LogisticRegression(class_weight='balanced')
log_model.fit(x_train_scaled, y_train)

LogisticRegression(class_weight='balanced')

In [33]:
y_pred = log_model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97     18988
           1       0.00      0.00      0.00      1012

    accuracy                           0.95     20000
   macro avg       0.47      0.50      0.49     20000
weighted avg       0.90      0.95      0.92     20000

/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [35]:
rf_model = RandomForestClassifier(n_estimators=50)

rf_model.fit(x_train_scaled, y_train)

RandomForestClassifier(n_estimators=50)

In [36]:
rf_y_pred = rf_model.predict(x_test)
print(classification_report(y_test, rf_y_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97     18988
           1       0.06      0.01      0.01      1012

    accuracy                           0.94     20000
   macro avg       0.51      0.50      0.49     20000
weighted avg       0.90      0.94      0.92     20000

In [37]:
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

xgb_model = XGBClassifier(scale_pos_weight=scale_pos_weight)
xgb_model.fit(x_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [38]:
xgb_y_pred = xgb_model.predict(x_test)
print(classification_report(xgb_y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97     20000
           1       0.00      0.00      0.00         0

    accuracy                           0.95     20000
   macro avg       0.50      0.47      0.49     20000
weighted avg       1.00      0.95      0.97     20000

/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/theslender/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))