In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_csv('other_data/Bank_Transaction_Fraud_Detection.csv')

In [24]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [25]:
df.shape

(200000, 24)

In [26]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'State', 'City',
       'Bank_Branch', 'Account_Type', 'Transaction_ID', 'Transaction_Date',
       'Transaction_Time', 'Transaction_Amount', 'Merchant_ID',
       'Transaction_Type', 'Merchant_Category', 'Account_Balance',
       'Transaction_Device', 'Transaction_Location', 'Device_Type', 'Is_Fraud',
       'Transaction_Currency', 'Customer_Contact', 'Transaction_Description',
       'Customer_Email'],
      dtype='object')

In [27]:
columns_to_drop = ["Customer_ID","Customer_Name", "Transaction_ID", "Merchant_ID","Customer_Contact","Transaction_Description", "Customer_Email", "Transaction_Currency"]
df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [28]:
df.head()

,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_Date,Transaction_Time,Transaction_Amount,Transaction_Type,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud
0,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,23-01-2025,16:04:07,32415.45,Transfer,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0
1,Female,51,Maharashtra,Nashik,Nashik Branch,Business,11-01-2025,17:14:53,43622.60,Bill Payment,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0
2,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,25-01-2025,03:09:52,63062.56,Bill Payment,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0
3,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,19-01-2025,12:27:02,14000.72,Debit,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0
4,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,30-01-2025,18:30:46,18335.16,Transfer,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  object
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  object
 3   City                  200000 non-null  object
 4   Bank_Branch           200000 non-null  object
 5   Account_Type          200000 non-null  object
 6   Transaction_Date      200000 non-null  object
 7   Transaction_Time      200000 non-null  object
 8   Transaction_Amount    200000 non-null  float64
 9   Transaction_Type      200000 non-null  object
 10  Merchant_Category     200000 non-null  object
 11  Account_Balance       200000 non-null  float64
 12  Transaction_Device    200000 non-null  object
 13  Transaction_Location  200000 non-null  object
 14  Device_Type           200000 non-null  object
 15  Is_Fraud              200000 non-null  int64
dtypes: float64(2), int64(2), object(12)
memory usage: 24.4+ MB

In [30]:
df["year"] = pd.to_datetime(df["Transaction_Date"]).dt.year
df["month"] = pd.to_datetime(df["Transaction_Date"]).dt.month
df["day"] = pd.to_datetime(df["Transaction_Date"]).dt.day

df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.hour
df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.minute
df["hour"] = pd.to_datetime(df["Transaction_Time"], format="%H:%M:%S").dt.second

df.drop(["Transaction_Time", "Transaction_Date"], axis=1, inplace=True)

/tmp/ipykernel_119980/1088819859.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["year"] = pd.to_datetime(df["Transaction_Date"]).dt.year
/tmp/ipykernel_119980/1088819859.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["month"] = pd.to_datetime(df["Transaction_Date"]).dt.month
/tmp/ipykernel_119980/1088819859.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["day"] = pd.to_datetime(df["Transaction_Date"]).dt.day

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Gender                200000 non-null  object
 1   Age                   200000 non-null  int64
 2   State                 200000 non-null  object
 3   City                  200000 non-null  object
 4   Bank_Branch           200000 non-null  object
 5   Account_Type          200000 non-null  object
 6   Transaction_Amount    200000 non-null  float64
 7   Transaction_Type      200000 non-null  object
 8   Merchant_Category     200000 non-null  object
 9   Account_Balance       200000 non-null  float64
 10  Transaction_Device    200000 non-null  object
 11  Transaction_Location  200000 non-null  object
 12  Device_Type           200000 non-null  object
 13  Is_Fraud              200000 non-null  int64
 14  year                  200000 non-null  int32
 15  month                 200000 non-null  int32
 16  day                   200000 non-null  int32
 17  hour                  200000 non-null  int32
dtypes: float64(2), int32(4), int64(2), object(10)
memory usage: 24.4+ MB

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.isnull().sum()

Gender                  0
Age                     0
State                   0
City                    0
Bank_Branch             0
Account_Type            0
Transaction_Amount      0
Transaction_Type        0
Merchant_Category       0
Account_Balance         0
Transaction_Device      0
Transaction_Location    0
Device_Type             0
Is_Fraud                0
year                    0
month                   0
day                     0
hour                    0
dtype: int64

In [36]:
Categorical = [i for i in df.columns if df[i].dtype == 'O']
Numerical = [i for i in df.columns if df[i].dtype != 'O']

In [37]:
print(f"Categorical: \n{Categorical}\n\nNumerical: \n{Numerical}")

Categorical:
['Gender', 'State', 'City', 'Bank_Branch', 'Account_Type', 'Transaction_Type', 'Merchant_Category', 'Transaction_Device', 'Transaction_Location', 'Device_Type']

Numerical:
['Age', 'Transaction_Amount', 'Account_Balance', 'Is_Fraud', 'year', 'month', 'day', 'hour']